apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default       # namespace where the pods are
  name: airflow-pods-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-pods-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: airflow-worker
  namespace: airflow
roleRef:
  kind: Role
  name: airflow-pods-role
  apiGroup: rbac.authorization.k8s.io