apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sparkoperator-access
  namespace: default
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "sparkapplications/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-sparkoperator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: airflow
roleRef:
  kind: Role
  name: sparkoperator-access
  apiGroup: rbac.authorization.k8s.io
